# Generated by Django 3.1 on 2020-08-19 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FinalYearProject', '0003_auto_20200819_0259'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImages1',
        ),
        migrations.DeleteModel(
            name='Products1',
        ),
    ]
